#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
THIRDPARTY_DIR="$ROOT_DIR/src/thirdparty"
UPSTREAM_DIR="$THIRDPARTY_DIR/sdsl-lite"
SUBSET_DIR="$THIRDPARTY_DIR/sdsl_subset"

if [[ ! -d "$UPSTREAM_DIR/.git" ]]; then
  echo "Expected upstream clone at $UPSTREAM_DIR (with .git)" >&2
  exit 1
fi

UPSTREAM_COMMIT="$(git -C "$UPSTREAM_DIR" rev-parse HEAD)"
UPSTREAM_URL="$(git -C "$UPSTREAM_DIR" remote get-url origin)"

headers=(bits.hpp config.hpp int_vector.hpp int_vector_buffer.hpp io.hpp iterators.hpp memory_management.hpp ram_filebuf.hpp ram_fs.hpp sdsl_concepts.hpp sfstream.hpp structure_tree.hpp uintx_t.hpp util.hpp)
sources=(bits.cpp io.cpp memory_management.cpp ram_filebuf.cpp ram_fs.cpp sfstream.cpp structure_tree.cpp util.cpp)

rm -rf "$SUBSET_DIR"
mkdir -p "$SUBSET_DIR/include/sdsl" "$SUBSET_DIR/lib" "$SUBSET_DIR/src"

cp "$UPSTREAM_DIR/COPYING" "$SUBSET_DIR/"
cp "$UPSTREAM_DIR/README.md" "$SUBSET_DIR/UPSTREAM_README.md"

for h in "${headers[@]}"; do cp "$UPSTREAM_DIR/include/sdsl/$h" "$SUBSET_DIR/include/sdsl/$h"; done
for s in "${sources[@]}"; do cp "$UPSTREAM_DIR/lib/$s" "$SUBSET_DIR/src/$s"; done

cat > "$SUBSET_DIR/Makefile" <<'MK'
PREFIX ?= ..
CXX ?= g++
AR ?= ar
CXXFLAGS ?= -std=c++17 -O3 -DNDEBUG
CPPFLAGS ?= -Iinclude

SOURCES := $(wildcard src/*.cpp)
OBJECTS := $(SOURCES:.cpp=.o)
LIB := lib/libsdsl.a

all: $(LIB)

$(LIB): $(OBJECTS)
	@mkdir -p lib
	$(AR) rcs $@ $^

src/%.o: src/%.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

install: $(LIB)
	mkdir -p $(PREFIX)/include/sdsl $(PREFIX)/lib
	cp -a include/sdsl/*.hpp $(PREFIX)/include/sdsl/
	cp -a $(LIB) $(PREFIX)/lib/

clean:
	rm -f src/*.o lib/libsdsl.a

.PHONY: all install clean
MK

{
  echo "# sdsl subset manifest"
  echo
  echo "- Upstream repository: $UPSTREAM_URL"
  echo "- Upstream commit: \`$UPSTREAM_COMMIT\`"
  echo "- Generated by: \`tools/vendor_sdsl_subset.sh\`"
  echo
  echo "## Included headers"
  for h in "${headers[@]}"; do echo "- include/sdsl/$h"; done
  echo
  echo "## Included source files"
  for s in "${sources[@]}"; do echo "- src/$s"; done
} > "$SUBSET_DIR/MANIFEST.md"

echo "Wrote subset to $SUBSET_DIR from $UPSTREAM_COMMIT"
